backend:
  name: github
  repo: washingtonsteven/stevenwa-sh
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: content/posts
    create: true
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle, required: false }
      - { name: featured_image, label: Featured Image, widget: image }
      - { name: featured, label: Featured, widget: boolean, default: false }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    label_singular: Project
    folder: content/projects
    create: true
    slug: "{{slug}}"
    preview_path: "projects/{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: featured_image, label: Featured Image, widget: image }
      - { name: featured, label: Featured, widget: boolean, default: true }
      - { name: tags, label: Tags, widget: list }
      - { name: repo, label: Repo }
      - { name: body, label: Body, widget: markdown }
      - {
          name: screenshots,
          label: Screenshots,
          widget: list,
          field: { name: image, label: Image, widget: image },
        }
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: content/pages/index.yml
        fields:
          - {
              label: "Template Key",
              name: "template_key",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "About Title", name: about_title, widget: string }
          - { label: "About Text", name: about_content, widget: markdown }
          - label: "Web Links"
            name: web_links
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Color, name: color, widget: string }
          - label: "Social Links"
            name: social_links
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Color, name: color, widget: string }
