backend:
  name: github
  repo: washingtonsteven/stevenwa-sh

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: src/pages/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
      - { name: featured_image, label: Featured Image, widget: image }
      - { name: published, label: Published, widget: boolean, default: true }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: src/pages/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: featured_image, label: Featured Image, widget: image }
      - { name: published, label: Published, widget: boolean, default: true }
      - { name: featured, label: Featured, widget: boolean, default: true }
      - { name: tags, label: Tags, widget: list }
      - { name: repo, label: Repo }
      - { name: body, label: Body, widget: markdown }
